### ISSUE TITLE
Remove extra height

### ISSUE THREAD

**Issue by 4goodapp** [joostkremers/nswbuff#3]
Thanks for this amazing package.
Is it possible to remove the extra hight completely? 
If possible shows buffers' names only in the echo area.
It was small in the beginning but now it's getting bigger.

![image](https://user-images.githubusercontent.com/6249230/54483055-4f300080-4845-11e9-996a-c9b4303b88b7.png)

![image](https://user-images.githubusercontent.com/6249230/54483148-05481a00-4847-11e9-9538-1685afe63f95.png)

**Comment by joostkremers** [comment]
This is weird, I've never seen this. What Emacs version do you have? Does it always start out small after restarting Emacs? Does it slowly increase (for example, a line is added each time you call `nswbuff-next-buffer`), or is it small for a while and then suddenly very big? If the latter, is there something specific that you do that seems to trigger it? Does it become smaller again? Have you customised `nswbuff` in any way?

Sorry, I have lots of questions... But I really have no idea what might be going on here.

**Comment by 4goodapp** [comment]
> If the latter, is there something specific that you do that seems to trigger it? 

I got it now, am using golden-ratio. So excluding the buffer will solve the issue.

**Comment by joostkremers** [comment]
Ah, thanks for letting me know! I'll add a note about that to the README.
