### ISSUE TITLE
wierd interaction with tabbar

### ISSUE THREAD

**Issue by jclosure** [joostkremers/nswbuff#5]
When using tabbar, nswbuff is showing the tabs for excluded buffers at the top of the status window.  Any idea why?

![image](https://user-images.githubusercontent.com/343099/66704643-7bc8cf80-ece3-11e9-8e2a-88ba9bea69ee.png)

**Comment by joostkremers** [comment]
Do you mean the `tabbar` package available here: https://github.com/dholm/tabbar ?

**Comment by jclosure** [comment]
Yeah, [tabbar](https://www.emacswiki.org/emacs) is fast and mature.  I use nswbuff w/ C-TAB to switch between buffers (tabs) in terminal via ssh emacs.  It's a joy to use, because it feels like a just like a gui editor.  The only issue is this artifact at the bottom.  Somehow the status window is picking up additional data to show.  Here's a simple config (same as the one shown above in the screenshot):

```elisp
(use-package tabbar
  :hook (after-init . tabbar-mode)
  :config
  (progn
    ;; style faces
    (progn
      (set-face-attribute
       'tabbar-default nil
       :background "gray20"
       :foreground "gray20"
       :box '(:line-width 1 :color "gray20" :style nil))

      (set-face-attribute
       'tabbar-unselected nil
       :background "gray30"
       :foreground "white"
       :underline nil
       :box '(:line-width 5 :color "gray30" :style nil))

      (set-face-attribute
       'tabbar-modified nil
       :background "gray30"
       :foreground "red"
       :underline nil
       :box '(:line-width 5 :color "gray30" :style nil))

      (set-face-attribute
       'tabbar-selected nil
       :background "white"
       :foreground "black"
       :underline nil
       :box '(:line-width 5 :color "white" :style nil))

      (set-face-attribute
       'tabbar-highlight nil
       :background "DarkCyan"
       :foreground "green"
       :underline nil
       :box '(:color "DarkCyan" :style nil))

      (set-face-attribute
       'tabbar-button nil
       :underline nil
       :box '(:line-width 1 :color "white" :style nil))

      (set-face-attribute
       'tabbar-unselected nil
       :background "gray34"
       :foreground "white"
       :box '(:line-width 1 :color "white" :style released-button))

      (set-face-attribute
       'tabbar-modified nil
       :background "gray34"
       :foreground "pink"
       :inherit 'tabbar-unselected
       :box '(:line-width 1 :color "white" :style released-button))

      (set-face-attribute
       'tabbar-selected nil
       :background "#bcbcbc"
       :foreground "black"
       :box nil)

      (set-face-attribute
       'tabbar-button nil
       :box '(:line-width 1 :color "gray72" :style released-button))

      (set-face-attribute
       'tabbar-separator nil
       :height 0.7)

      (set-face-attribute
       'tabbar-button nil
       :inherit 'tabbar-default-face
       :box '(:line-width 1 :color "gray30"))

      (set-face-attribute 'tabbar-default  nil
			  :height 1.1)

      (set-face-attribute
       'tabbar-selected nil
       :inherit 'tabbar-default-face
       :foreground "blue3"
       :background "LightGoldenrod"
       :box '(:line-width 1 :color "DarkGoldenrod")
       :weight 'bold)

      (set-face-attribute
       'tabbar-unselected nil
       :inherit 'tabbar-default-face
       :box '(:line-width 1 :color "gray70")))))

**Comment by jclosure** [comment]
My guess is that the same issue will exist with [centaur-tabs](https://github.com/ema2159/centaur-tabs) as well since it's a fork of tabbar.

**Comment by joostkremers** [comment]
I mainly asked because there's currently work going on to implement a native tab bar in Emacs, so I was wondering which tab bar you meant.

The easiest way to deal with this would be if you could tell `tabbar` to not display a tab bar in the buffer used by `nswbuff`. Its name is `" *nswbuff*"` (without the double quotes, of course; note the space at the beginning), though you can also use the variable `nswbuff-status-buffer-name` to refer to it.

**Comment by jclosure** [comment]
Ahh yes.  That works perfectly.  Here's the solution. You basically tell tabbar to ignore the nswbuff status buffer.

```elisp
    (setq *tabbar-ignore-buffers* '(" *nswbuff*"))
    (setq tabbar-buffer-list-function
          (lambda ()
            (remove-if
             (lambda (buffer)
               (loop for name in *tabbar-ignore-buffers* ;remove buffer name in this list.
                          thereis (string-equal (buffer-name buffer) name)))
             (buffer-list))))
```
Thank you.  

Yes, I'm also looking forward to the native tabs impl.  Getting a standardized approach to tabs will really be nice.

**Comment by joostkremers** [comment]
Reading about `tabbar.el` a bit, it seems to me that the behaviour you're seeing is actually exactly what's expected, even though I admit it looks weird at first. `tabbar.el` displays a tab bar in each window, and by default it groups buffers by major mode. The `nswbuff` buffer is in `fundamental-mode`, and I suspect the other buffers in the tab bar use the same mode.

Thanks for posting that config snippet. If anyone runs into the same issue, there's a solution here.
